main: com.katok.languageapi.LanguageAPI
name: LanguageAPI
version: '1.0'
author: Katok777
api-version: 1.16

commands:
  languageapi:
    usage: "/languageapi"

permissions:
  languageapi.reload:
    default: op

depend:
  - "PlaceholderAPI"